name: Build

on:
  push:
    branches-ignore:
      - dependabot/**

jobs:
  run-ci:
    uses: Jikoo/PlanarActions/.github/workflows/ci_maven.yml@master
    with:
      java-version: "25"
      include-artifacts: "plugin/target/Regionerator.jar"
